"""Airport IATA code to city name lookup.

Embedded database of major airports for resolving route endpoints
to human-readable labels like 'Frankfurt FRA'.
"""

_AIRPORTS: dict[str, str] = {
    # ── Germany ──
    "FRA": "Frankfurt",
    "MUC": "Munich",
    "BER": "Berlin",
    "DUS": "Düsseldorf",
    "HAM": "Hamburg",
    "CGN": "Cologne",
    "STR": "Stuttgart",
    "HAJ": "Hannover",
    "NUE": "Nuremberg",
    "LEJ": "Leipzig",
    "DTM": "Dortmund",
    "FMO": "Münster",
    "BRE": "Bremen",
    "DRS": "Dresden",
    "PAD": "Paderborn",
    "SCN": "Saarbrücken",
    "ERF": "Erfurt",
    "FDH": "Friedrichshafen",
    "FKB": "Karlsruhe",
    "HHN": "Hahn",
    "NRN": "Weeze",
    "GWT": "Sylt",
    "LBC": "Lübeck",
    "RLG": "Rostock",
    "FMM": "Memmingen",
    # ── Italy ──
    "FCO": "Rome",
    "CIA": "Rome Ciampino",
    "MXP": "Milan Malpensa",
    "LIN": "Milan Linate",
    "BGY": "Bergamo",
    "VCE": "Venice",
    "NAP": "Naples",
    "BLQ": "Bologna",
    "CAG": "Cagliari",
    "CTA": "Catania",
    "PMO": "Palermo",
    "FLR": "Florence",
    "PSA": "Pisa",
    "TRN": "Turin",
    "VRN": "Verona",
    "BRI": "Bari",
    "OLB": "Olbia",
    "AHO": "Alghero",
    "SUF": "Lamezia",
    "GOA": "Genoa",
    "TRS": "Trieste",
    "BDS": "Brindisi",
    "REG": "Reggio Calabria",
    "PEG": "Perugia",
    "AOI": "Ancona",
    "GRS": "Grosseto",
    # ── UK & Ireland ──
    "LHR": "London Heathrow",
    "LGW": "London Gatwick",
    "STN": "London Stansted",
    "LTN": "London Luton",
    "LCY": "London City",
    "MAN": "Manchester",
    "EDI": "Edinburgh",
    "BHX": "Birmingham",
    "GLA": "Glasgow",
    "BRS": "Bristol",
    "LPL": "Liverpool",
    "NCL": "Newcastle",
    "EMA": "East Midlands",
    "ABZ": "Aberdeen",
    "BFS": "Belfast",
    "BHD": "Belfast City",
    "CWL": "Cardiff",
    "SOU": "Southampton",
    "EXT": "Exeter",
    "INV": "Inverness",
    "JER": "Jersey",
    "GCI": "Guernsey",
    "DUB": "Dublin",
    "SNN": "Shannon",
    "ORK": "Cork",
    "KNO": "Knock",
    # ── France ──
    "CDG": "Paris CDG",
    "ORY": "Paris Orly",
    "NCE": "Nice",
    "LYS": "Lyon",
    "MRS": "Marseille",
    "TLS": "Toulouse",
    "BOD": "Bordeaux",
    "NTE": "Nantes",
    "SXB": "Strasbourg",
    "BIQ": "Biarritz",
    "MPL": "Montpellier",
    "BVA": "Beauvais",
    "RNS": "Rennes",
    "LIL": "Lille",
    "MLH": "Mulhouse",
    "AJA": "Ajaccio",
    "BIA": "Bastia",
    "CFE": "Clermont-Ferrand",
    # ── Spain & Portugal ──
    "MAD": "Madrid",
    "BCN": "Barcelona",
    "PMI": "Palma de Mallorca",
    "AGP": "Malaga",
    "ALC": "Alicante",
    "IBZ": "Ibiza",
    "TFS": "Tenerife South",
    "TFN": "Tenerife North",
    "LPA": "Gran Canaria",
    "ACE": "Lanzarote",
    "FUE": "Fuerteventura",
    "SVQ": "Seville",
    "VLC": "Valencia",
    "BIO": "Bilbao",
    "SCQ": "Santiago",
    "GRO": "Girona",
    "REU": "Reus",
    "MAH": "Menorca",
    "XRY": "Jerez",
    "MJV": "Murcia",
    "LIS": "Lisbon",
    "OPO": "Porto",
    "FAO": "Faro",
    "FNC": "Funchal",
    "PDL": "Ponta Delgada",
    # ── Benelux ──
    "AMS": "Amsterdam",
    "EIN": "Eindhoven",
    "RTM": "Rotterdam",
    "MST": "Maastricht",
    "GRQ": "Groningen",
    "BRU": "Brussels",
    "CRL": "Charleroi",
    "ANR": "Antwerp",
    "LGG": "Liège",
    "LUX": "Luxembourg",
    # ── Switzerland & Austria ──
    "ZRH": "Zurich",
    "GVA": "Geneva",
    "BSL": "Basel",
    "BRN": "Bern",
    "LUG": "Lugano",
    "VIE": "Vienna",
    "SZG": "Salzburg",
    "INN": "Innsbruck",
    "GRZ": "Graz",
    "LNZ": "Linz",
    "KLU": "Klagenfurt",
    # ── Scandinavia & Baltics ──
    "CPH": "Copenhagen",
    "ARN": "Stockholm Arlanda",
    "BMA": "Stockholm Bromma",
    "GOT": "Gothenburg",
    "MMX": "Malmö",
    "OSL": "Oslo",
    "BGO": "Bergen",
    "TRD": "Trondheim",
    "SVG": "Stavanger",
    "HEL": "Helsinki",
    "TMP": "Tampere",
    "TLL": "Tallinn",
    "RIX": "Riga",
    "VNO": "Vilnius",
    "KUN": "Kaunas",
    # ── Eastern Europe ──
    "WAW": "Warsaw",
    "KRK": "Krakow",
    "GDN": "Gdansk",
    "WRO": "Wroclaw",
    "KTW": "Katowice",
    "POZ": "Poznan",
    "PRG": "Prague",
    "BTS": "Bratislava",
    "BUD": "Budapest",
    "OTP": "Bucharest",
    "CLJ": "Cluj",
    "SOF": "Sofia",
    "VAR": "Varna",
    "BOJ": "Bourgas",
    "ZAG": "Zagreb",
    "SPU": "Split",
    "DBV": "Dubrovnik",
    "PUY": "Pula",
    "ZAD": "Zadar",
    "BEG": "Belgrade",
    "LJU": "Ljubljana",
    "SKP": "Skopje",
    "TIA": "Tirana",
    "PRN": "Pristina",
    # ── Greece & Cyprus ──
    "ATH": "Athens",
    "SKG": "Thessaloniki",
    "HER": "Heraklion",
    "CHQ": "Chania",
    "RHO": "Rhodes",
    "CFU": "Corfu",
    "JMK": "Mykonos",
    "JTR": "Santorini",
    "ZTH": "Zakynthos",
    "KGS": "Kos",
    "EFL": "Kefalonia",
    "LCA": "Larnaca",
    "PFO": "Paphos",
    "ECN": "Ercan",
    # ── Turkey ──
    "IST": "Istanbul",
    "SAW": "Istanbul Sabiha",
    "ESB": "Ankara",
    "AYT": "Antalya",
    "ADB": "Izmir",
    "DLM": "Dalaman",
    "BJV": "Bodrum",
    "TZX": "Trabzon",
    "GZT": "Gaziantep",
    # ── Middle East ──
    "DXB": "Dubai",
    "AUH": "Abu Dhabi",
    "DOH": "Doha",
    "BAH": "Bahrain",
    "KWI": "Kuwait",
    "MCT": "Muscat",
    "RUH": "Riyadh",
    "JED": "Jeddah",
    "AMM": "Amman",
    "BEY": "Beirut",
    "TLV": "Tel Aviv",
    # ── North Africa ──
    "CAI": "Cairo",
    "HRG": "Hurghada",
    "SSH": "Sharm el-Sheikh",
    "CMN": "Casablanca",
    "RAK": "Marrakech",
    "TUN": "Tunis",
    "ALG": "Algiers",
    "TNG": "Tangier",
    # ── Sub-Saharan Africa ──
    "JNB": "Johannesburg",
    "CPT": "Cape Town",
    "NBO": "Nairobi",
    "ADD": "Addis Ababa",
    "LOS": "Lagos",
    "ACC": "Accra",
    "DKR": "Dakar",
    "DAR": "Dar es Salaam",
    "ZNZ": "Zanzibar",
    # ── North America ──
    "JFK": "New York JFK",
    "EWR": "Newark",
    "LGA": "New York LaGuardia",
    "LAX": "Los Angeles",
    "ORD": "Chicago O'Hare",
    "ATL": "Atlanta",
    "DFW": "Dallas",
    "DEN": "Denver",
    "SFO": "San Francisco",
    "SEA": "Seattle",
    "MIA": "Miami",
    "BOS": "Boston",
    "IAD": "Washington Dulles",
    "DCA": "Washington Reagan",
    "BWI": "Baltimore",
    "PHL": "Philadelphia",
    "CLT": "Charlotte",
    "MSP": "Minneapolis",
    "DTW": "Detroit",
    "IAH": "Houston",
    "PHX": "Phoenix",
    "SAN": "San Diego",
    "SLC": "Salt Lake City",
    "MCO": "Orlando",
    "TPA": "Tampa",
    "FLL": "Fort Lauderdale",
    "LAS": "Las Vegas",
    "HNL": "Honolulu",
    "ANC": "Anchorage",
    "PDX": "Portland",
    "RDU": "Raleigh",
    "PIT": "Pittsburgh",
    "STL": "St. Louis",
    "IND": "Indianapolis",
    "AUS": "Austin",
    "BNA": "Nashville",
    "MCI": "Kansas City",
    "CLE": "Cleveland",
    "SMF": "Sacramento",
    "SJC": "San Jose",
    "OAK": "Oakland",
    "YYZ": "Toronto",
    "YUL": "Montreal",
    "YVR": "Vancouver",
    "YOW": "Ottawa",
    "YYC": "Calgary",
    "YEG": "Edmonton",
    "YHZ": "Halifax",
    "YWG": "Winnipeg",
    "MEX": "Mexico City",
    "CUN": "Cancún",
    "GDL": "Guadalajara",
    # ── South America ──
    "GRU": "São Paulo",
    "GIG": "Rio de Janeiro",
    "EZE": "Buenos Aires",
    "SCL": "Santiago Chile",
    "BOG": "Bogotá",
    "LIM": "Lima",
    "PTY": "Panama City",
    "UIO": "Quito",
    "CCS": "Caracas",
    "MVD": "Montevideo",
    # ── Caribbean ──
    "SJU": "San Juan",
    "NAS": "Nassau",
    "BGI": "Barbados",
    "POS": "Port of Spain",
    "MBJ": "Montego Bay",
    "AUA": "Aruba",
    "CUR": "Curaçao",
    "SXM": "Sint Maarten",
    "PUJ": "Punta Cana",
    "HAV": "Havana",
    # ── Asia ──
    "PEK": "Beijing",
    "PVG": "Shanghai Pudong",
    "SHA": "Shanghai Hongqiao",
    "CAN": "Guangzhou",
    "HKG": "Hong Kong",
    "NRT": "Tokyo Narita",
    "HND": "Tokyo Haneda",
    "KIX": "Osaka",
    "ICN": "Seoul Incheon",
    "GMP": "Seoul Gimpo",
    "SIN": "Singapore",
    "BKK": "Bangkok",
    "KUL": "Kuala Lumpur",
    "CGK": "Jakarta",
    "DPS": "Bali",
    "MNL": "Manila",
    "DEL": "Delhi",
    "BOM": "Mumbai",
    "BLR": "Bangalore",
    "MAA": "Chennai",
    "CCU": "Kolkata",
    "HYD": "Hyderabad",
    "CMB": "Colombo",
    "DAC": "Dhaka",
    "KTM": "Kathmandu",
    "HAN": "Hanoi",
    "SGN": "Ho Chi Minh City",
    "TPE": "Taipei",
    "MLE": "Malé",
    "ISB": "Islamabad",
    "KHI": "Karachi",
    "LHE": "Lahore",
    "TAS": "Tashkent",
    "ALA": "Almaty",
    "NQZ": "Astana",
    "TBS": "Tbilisi",
    "EVN": "Yerevan",
    "GYD": "Baku",
    # ── Oceania ──
    "SYD": "Sydney",
    "MEL": "Melbourne",
    "BNE": "Brisbane",
    "PER": "Perth",
    "AKL": "Auckland",
    "WLG": "Wellington",
    "CHC": "Christchurch",
    "NAN": "Nadi",
    "PPT": "Tahiti",
    # ── Russia & CIS (common overflights) ──
    "SVO": "Moscow",
    "DME": "Moscow Domodedovo",
    "LED": "St. Petersburg",
    "KZN": "Kazan",
    # ── Iceland ──
    "KEF": "Reykjavik",
    # ── Malta ──
    "MLA": "Malta",
}


def airport_city(iata: str) -> str | None:
    """Return the city/airport name for an IATA code, or None if unknown."""
    return _AIRPORTS.get(iata.upper()) if iata else None


def format_route_endpoint(iata: str) -> str:
    """Format an IATA code as 'City (CODE)' or just 'CODE' if unknown."""
    if not iata:
        return ""
    city = airport_city(iata)
    if city:
        return f"{city} ({iata.upper()})"
    return iata.upper()


def format_route(origin: str | None, destination: str | None) -> str | None:
    """Format a full route string, or None if no route data."""
    if origin and destination:
        return f"{format_route_endpoint(origin)}  →  {format_route_endpoint(destination)}"
    if origin:
        return f"From {format_route_endpoint(origin)}"
    if destination:
        return f"To {format_route_endpoint(destination)}"
    return None
